apiVersion: v1
kind: ConfigMap
metadata:
  name: photowebapp-backend-config
  namespace: photowebapp-paas
  labels:
    app.kubernetes.io/part-of: PhotoWebApp_PAAS
data:
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_NAME: gallery
