apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: photowebapp-paas
  labels:
    app.kubernetes.io/part-of: PhotoWebApp_PAAS
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
