apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: photowebapp-paas
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: PhotoWebApp_PAAS
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
