apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-data
  namespace: photowebapp-paas
  labels:
    app.kubernetes.io/name: photowebapp-uploads
    app.kubernetes.io/part-of: PhotoWebApp_PAAS
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
