apiVersion: v1
kind: Secret
metadata:
  name: photowebapp-app-secret
  namespace: photowebapp-paas
  labels:
    app.kubernetes.io/name: photowebapp
    app.kubernetes.io/part-of: PhotoWebApp_PAAS
type: Opaque
stringData:
  SECRET_KEY: CHANGE_ME_STRONG_APP_SECRET
  DB_USER: gallery
  DB_PASSWORD: CHANGE_ME_STRONG_DB_PASSWORD
