apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: photowebapp-paas
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: PhotoWebApp_PAAS
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 32000
