CREATE TABLE IF NOT EXISTS photos (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(40) NOT NULL,
  tags VARCHAR(255) NULL,
  upload_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  file_path_or_url VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);
