apiVersion: v1
kind: Secret
metadata:
  name: photowebapp-db-secret
  namespace: photowebapp-paas
  labels:
    app.kubernetes.io/name: photowebapp
    app.kubernetes.io/part-of: PhotoWebApp_PAAS
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: CHANGE_ME_STRONG_ROOT_PASSWORD
  MYSQL_PASSWORD: CHANGE_ME_STRONG_DB_PASSWORD
